<<<<<<< HEAD
# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
=======
# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
>>>>>>> 876b41aeb823c6e366286fa3d8fee5e3c2b1eb21
